### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by adri123** [guyhoffman/podpuller#3]
Hello,
I get the following bug when lauching the command :

` ```
~ podpuller
Traceback (most recent call last):
  File "/usr/local/bin/podpuller", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/podpuller/podpuller.py", line 142, in main
    init_db(directories["data"])
  File "/usr/local/lib/python3.9/site-packages/podpuller/db.py", line 21, in init_db
    Episode.createTable(ifNotExists=True)
  File "/usr/local/lib/python3.9/site-packages/sqlobject/main.py", line 1498, in createTable
    if ifNotExists and cls.tableExists(connection=conn):
  File "/usr/local/lib/python3.9/site-packages/sqlobject/main.py", line 1473, in tableExists
    return conn.tableExists(cls.sqlmeta.table)
  File "/usr/local/lib/python3.9/site-packages/sqlobject/sqlite/sqliteconnection.py", line 306, in tableExists
    result = self.queryOne(
  File "/usr/local/lib/python3.9/site-packages/sqlobject/dbconnection.py", line 481, in queryOne
    return self._runWithConnection(self._queryOne, s)
  File "/usr/local/lib/python3.9/site-packages/sqlobject/dbconnection.py", line 340, in _runWithConnection
    conn = self.getConnection()
  File "/usr/local/lib/python3.9/site-packages/sqlobject/sqlite/sqliteconnection.py", line 160, in getConnection
    conn = self.makeConnection()
  File "/usr/local/lib/python3.9/site-packages/sqlobject/sqlite/sqliteconnection.py", line 210, in makeConnection
    conn = self.module.connect(self.filename, **self._connOptions)
sqlite3.OperationalError: unable to open database file`
```

**Comment by guyhoffman** [comment]
This looks like you might not have write permission to the directory that you specified as your data dir. Can you share your config files?

**Comment by adri123** [comment]
I didn't have the download directories created, thats why the app could not create or read the database.
Thanks,
